name: Deploy to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fix npm vulnerabilities
        run: npm audit fix

      - name: Build with Gradle
        run: ./gradlew build

      - name: SSH and Delete application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:
            pkill -9 -f circlespace.jar

      - name: Upload to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/circlespace.jar"
          target: "/home/ubuntu/"
          strip_components: 2

      - name: SSH and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mv circlespace.log /home/ubuntu/logs/circlespace_$(date +'%Y%m%d_%H%M%S').log || echo "No log to move"
            java -Duser.timezone=Asia/Seoul -jar circlespace.jar > circlespace.log 2>&1 &

